### ISSUE TITLE
The icon blank ratio is different from that of Windows Boot Manager

### ISSUE THREAD

**Issue by AzarAI-TOP** [KZ25T/Windows-like-grub#1]
The blank ratio of the icons of Windows Boot Manager is about 25%, but the ratio of the icons in *src* is about 50% which makes the icon not fiting in.

**Comment by KZ25T** [comment]
I have fixed that in the new commit and new release. You can adjust it yourself by getting icon files in the link in README and do it yourself. Thanks a lot.
